const data={
"visit":{eye:"Visit",title:"Plan your visit",lead:"Step into a museum unlike any other.",body:"The Museum of Love is being developed as a physical cultural destination in Spain. Final location, opening date, hours and ticket information will be published here once confirmed.",cta:"Get opening updates"},
"100-stories":{eye:"The physical exhibition",title:"100 Stories",lead:"A new exhibition. Every month.",body:"Every month, 100 real stories of love, connection and the people who matter to us enter the galleries. Then the exhibition changes completely. The curation spans romantic love, friendship, family, distance, beginnings, second chances and remembrance.",cta:"Share your story"},
"story-room":{eye:"Create",title:"The Story Room",lead:"Step inside together. Tell your story. Take it with you.",body:"A private room. A professional recording. Simple prompts if you want them. Your finished digital Museum of Love piece is included with admission and delivered to you to keep and share.",cta:"How it works"},
"online-museum":{eye:"Online Museum",title:"30 Stories. Every month.",lead:"A curated selection, free for everyone to explore.",body:"Thirty stories are selected each month for the Online Museum. Stories are presented as an editorial exhibition—not a social feed. A €10 submission fee covers screening and editorial review; payment never guarantees selection.",cta:"Submit a story — €10"},
"love-office":{eye:"The Love Office",title:"Send something worth saying.",lead:"Some things deserve more than a message.",body:"Write a personal message to someone who matters. The Museum prepares it as a beautiful physical letter or card, applies the Museum of Love seal and date, and sends it to your recipient.",cta:"Send a message"},
"share-your-story":{eye:"Participate",title:"Share Your Story",lead:"Submit for the Online Museum.",body:"Tell us about your story and submit it for consideration in a future monthly Online Museum. Every submission is reviewed. Thirty are selected each month. The €10 fee covers editorial review and does not guarantee publication.",cta:"Begin submission — €10"},
"about":{eye:"About the Museum",title:"A living museum. A digital institution.",lead:"100 stories. Every month.",body:"The Museum combines rotating physical exhibitions with digital participation. The Story Room captures visitor-created stories and produces a shareable digital piece; consent-controlled systems can support transcription, subtitling and multilingual accessibility. The digital layer strengthens the museum experience without replacing it.",cta:"Explore 100 Stories"},
"faq":{eye:"Information",title:"Frequently asked questions",lead:"The Museum is currently in development.",body:"The website reflects the approved concept. Final venue, opening date, ticket prices, operating hours and fulfilment details are intentionally not presented as established facts until they are verified.",cta:"About the Museum"}
};
const links={"visit":"/","100-stories":"/share-your-story","story-room":"/story-room","online-museum":"/share-your-story","love-office":"/love-office","share-your-story":"/share-your-story","about":"/100-stories","faq":"/about"};
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}))}
export default async function Page({params}){const {slug}=await params;const d=data[slug];if(!d)return <main className="pageHero"><div><h1>Page not found</h1></div></main>;return <main><section className="pageHero"><div><div className="eyebrow">{d.eye}</div><h1>{d.title}</h1><p className="quote">{d.lead}</p><p>{d.body}</p><a className="button" href={links[slug]}>{d.cta}</a></div><div className="featureImage"/></section>{slug==="story-room"&&<section className="section"><h2>Your story, your way.</h2><div className="steps"><div className="step"><div className="number">01</div><h3>Choose</h3><p>Choose a story prompt—or tell it your way.</p></div><div className="step"><div className="number">02</div><h3>Record</h3><p>Record your story together in the room.</p></div><div className="step"><div className="number">03</div><h3>Keep</h3><p>Your digital version is free and ready to share.</p></div><div className="step"><div className="number">04</div><h3>Print</h3><p>Optional same-day museum print: €10. Later orders: €20 + shipping.</p></div></div></section>}{slug==="online-museum"&&<section className="section"><div className="stories">{["01","02","03"].map((n,i)=><article key={n}><div className="storyImage"/><div className="storyNo">{n} / 30</div><h3>{["We met on the same train for three years before either of us spoke.","A second chance at forty.","The letter that changed everything."][i]}</h3><a href="/story">Read the story →</a></article>)}</div></section>}{slug==="love-office"&&<section className="section"><div className="steps">{["Write your message","Choose recipient","We prepare it","We seal and send it"].map((x,i)=><div className="step" key={x}><div className="number">0{i+1}</div><h3>{x}</h3></div>)}</div></section>}{slug==="share-your-story"&&<section className="section"><div className="formMock"><div className="field">Your name / display name</div><div className="field">Tell us your story</div><div className="field">Photo or media</div><div className="field">Publication and privacy choices</div><p className="notice">Demo only. Submission/payment processing is not active. Final consent and legal terms require qualified legal review.</p></div></section>}</main>}